"""Build a 50-company fresh-data validity test.

DESIGN (three things make this a real test, not more self-checking):

1. THE LABEL IS EXTERNAL AND PRE-REGISTERED. Every prediction is derived from a
   PUBLISHED fact -- a price point, a store count, a market share, a documented
   closure -- never from my judgement of the business. Predictions are sealed in the
   input files before any run.

2. THE COMPETITIVE SET IS PER PRODUCT CATEGORY, HELD CONSTANT ACROSS THE MEMBERS.
   Positioning theory is about product categories, not industries. So each category
   gets ONE derived competitive set (tiers 0-7), and the companies vary within it.
   That scales up the koi/CaiCa design -- same derived evidence, different business --
   which is the only way to isolate the business as the variable.

3. CATEGORIES ARE CHOSEN BY PRICE STRUCTURE, because that is what the label needs.
   WIDE-spread categories can test ordering (the ends should separate from the
   undifferentiated middle). CONVERGED categories test the opposite claim: the rubric
   should report LOW differentiation because the category is commoditised. Bubble tea
   (267% spread) and petrol (0.3%) were the two poles; this set spans both.

WHAT WOULD FALSIFY IT
  * in a WIDE-spread category, the cheapest-or-premium brand scoring BELOW the
    undifferentiated mid-tier brand
  * in a CONVERGED category, a brand scoring as strongly differentiated as a
    wide-spread category's leader
  * a documented dead brand NOT refusing
  * systematic bias by category (all gyms high, all bakeries low)

HONEST LIMITS, stated up front:
  * I authored these input files. The LABELS are external; the FORM DATA is my
    reconstruction from public sources, which is thinner than a real submission.
  * Price position is a PROXY for positioning. The bubble tea test showed it is
    conditional, not mechanical (Gong Cha and KOI share S$4.50 and are opposites).
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "inputs-v2"
OUT.mkdir(exist_ok=True)

# ---------------------------------------------------------------------------
# DERIVED COMPETITIVE SETS — one per PRODUCT CATEGORY, reused by every member
# ---------------------------------------------------------------------------
CATS = {
    "bubble-tea": {
        "product_category": "Bubble tea / flavoured tea beverage, drunk on the go",
        "price_spread": "wide (S$1.50-5.50, 267%)",
        "tiers": {
            "tier_0_default": {"members": ["nothing / water", "hawker kopi ~S$1.20-2.00",
                                           "convenience-store bottled drinks ~S$1.50-2.50"],
                               "why": "Cheaper, no detour. Most drink occasions resolve here."},
            "tier_1_cheap_substitute": {"members": ["Mixue S$1.50-3.50", "hawker bubble tea stalls",
                                                    "Each-A-Cup budget line", "R&B Tea from ~S$3.60"],
                                        "why": "Cheapest cup on the island, positioned where students pass.",
                                        "price_floor": "S$1.50"},
            "tier_2_direct_set": {"members": ["LiHO TEA (~84 outlets)", "CHAGEE (46 outlets)",
                                              "Chicha San Chen (32)", "Playmade", "Sharetea",
                                              "HEYTEA", "KOI The (90)"],
                                  "why": "Same product, same occasion. 62+ brands, 953 businesses islandwide. Fragmented."},
            "tier_3_category_incumbent": {"members": ["KOI The - largest network, 90 outlets",
                                                      "CHAGEE - 'not a bubble tea brand, a tea expert'",
                                                      "LiHO - 'No.1 homegrown'"],
                                          "why": "The buyer is shopping for a TREAT DRINK. Each holds a rung of the mental ladder."},
            "tier_4_adjacent_crossover": {"members": ["specialty coffee", "dessert / shaved ice",
                                                      "convenience-store RTD tea"],
                                          "why": "Takes the same treat-drink occasion with a different product."},
            "tier_6_indirect": {"members": ["health messaging reducing treat frequency", "home brewing"],
                                "why": "Dilutes the number of treat occasions."},
            "tier_7_new_entrants": {"members": ["Molly Tea (Shenzhen, flagship Orchard Central Mar 2026)",
                                                "Black Tree (Shanghai Thai-tea, 313@somerset)",
                                                "Tealive (Malaysia, Changi T3)", "Mr. Sun Tea (Taiwan, *SCAPE)"],
                                    "why": "Derived from ACRA/new-opening records, not asked of the owner."},
        },
    },
    "gym": {
        "product_category": "Fitness gym membership, recurring access to train",
        "price_spread": "wide (S$15-400/mo, 26x)",
        "tiers": {
            "tier_0_default": {"members": ["no exercise", "home workouts / free YouTube",
                                           "running in the park", "HDB fitness corner"],
                               "why": "Free. Most exercise intentions resolve here."},
            "tier_1_cheap_substitute": {"members": ["ActiveSG MyActiveGYM S$15-30/mo, ~30 sites",
                                                    "SAFRA EnergyOne S$45-54", "condo gym (bundled)"],
                                        "why": "Government-run price floor every commercial gym is judged against.",
                                        "price_floor": "S$15/mo off-peak"},
            "tier_2_direct_set": {"members": ["Anytime Fitness (100+ outlets, 24/7)",
                                              "Fitness First (14 clubs)", "Virgin Active (5 clubs)",
                                              "Pure Fitness (2 clubs)", "24/7 Fitness"],
                                  "why": "Same product: a monthly membership to lift weights and take classes."},
            "tier_3_category_incumbent": {"members": ["ActiveSG - the default, cheapest, ubiquitous",
                                                      "Anytime Fitness - most outlets, 24/7 keycard",
                                                      "Fitness First - the established CBD chain"],
                                          "why": "Each holds a clear rung: cheapest / most accessible / most established."},
            "tier_4_adjacent_crossover": {"members": ["boutique studios (F45, Ritual, yoga)",
                                                      "personal trainers", "ClassPass"],
                                          "why": "Same goal (get fit), different delivery model."},
            "tier_6_indirect": {"members": ["sedentary lifestyle", "work-hours creep"],
                                "why": "Reduces the number of training occasions."},
            "tier_7_new_entrants": {"members": ["24/7 Fitness (growing)", "boutique studio openings"],
                                    "why": "Derived from new openings, not asked of the owner."},
        },
    },
    "supermarket": {
        "product_category": "Supermarket grocery retail, weekly household shop",
        "price_spread": "moderate (premium vs value shelf)",
        "tiers": {
            "tier_0_default": {"members": ["wet market", "hawker meals instead of cooking",
                                           "grow your own", "skip the meal"],
                               "why": "Cheaper or no purchase at all."},
            "tier_1_cheap_substitute": {"members": ["Giant (40 stores, value)",
                                                    "Sheng Siong (77 stores, no-frills)",
                                                    "online grocery (RedMart, Shopee)"],
                                        "why": "Lowest shelf price for the same basket.",
                                        "price_floor": "value shelf"},
            "tier_2_direct_set": {"members": ["NTUC FairPrice (125 stores)", "Sheng Siong (77)",
                                              "Cold Storage (48)", "Giant (40)", "Don Don Donki"],
                                  "why": "Same product: a weekly grocery basket. 691 stores islandwide."},
            "tier_3_category_incumbent": {"members": ["NTUC FairPrice - the national default, 125 stores",
                                                      "Sheng Siong - 'cheapest fresh', peer-leading margin",
                                                      "Cold Storage - the premium shop"],
                                          "why": "FairPrice owns 'default', Sheng Siong owns 'value+fresh', Cold Storage owns 'premium'."},
            "tier_4_adjacent_crossover": {"members": ["convenience stores (Cheers, 7-Eleven)",
                                                      "food delivery replacing home cooking",
                                                      "specialty grocers (Little Farms)"],
                                          "why": "Same need (feed the household) via a different channel."},
            "tier_6_indirect": {"members": ["JB cross-border shopping", "eating out instead of cooking"],
                                "why": "Removes the basket entirely."},
            "tier_7_new_entrants": {"members": ["Scarlett Supermarket (China-import, expanding)",
                                                "Little Farms (premium)", "Macrovalue's Cold Storage revamp"],
                                    "why": "Derived from new openings and the DFI ownership change."},
        },
    },
    "kopitiam": {
        "product_category": "Local coffee-shop breakfast: kaya toast and kopi",
        "price_spread": "moderate (S$4.20-8+ per set)",
        "tiers": {
            "tier_0_default": {"members": ["make coffee at home", "skip breakfast", "office pantry"],
                               "why": "Free or near-free."},
            "tier_1_cheap_substitute": {"members": ["hawker kopi stall ~S$1.20-2.00",
                                                    "foodcourt breakfast set"],
                                        "why": "Same product much cheaper, no branding.",
                                        "price_floor": "~S$1.20"},
            "tier_2_direct_set": {"members": ["Ya Kun Kaya Toast", "Killiney Kopitiam",
                                              "Toast Box", "Chin Mee Chin", "Tong Ah"],
                                  "why": "Same product: kaya toast set with kopi. Heritage branding is the axis."},
            "tier_3_category_incumbent": {"members": ["Ya Kun - the 1926 heritage standard, largest chain",
                                                      "Killiney - the 1919 rival heritage claim",
                                                      "Toast Box - BreadTalk's modern mass-market version"],
                                          "why": "Each owns a heritage/modern rung of the same mental ladder."},
            "tier_4_adjacent_crossover": {"members": ["cafe brunch", "bakery breakfast",
                                                      "McDonald's breakfast"],
                                          "why": "Same occasion, different product."},
            "tier_6_indirect": {"members": ["WFH reducing commute breakfasts"],
                                "why": "Removes the occasion."},
            "tier_7_new_entrants": {"members": ["specialty coffee chains", "new heritage-themed cafes"],
                                    "why": "Derived from new openings."},
        },
    },
    "bakery": {
        "product_category": "Bakery: packaged bread and buns for home consumption",
        "price_spread": "moderate (value loaf vs artisan)",
        "tiers": {
            "tier_0_default": {"members": ["supermarket house-brand bread", "rice instead"],
                               "why": "Cheaper, bought with the weekly shop."},
            "tier_1_cheap_substitute": {"members": ["supermarket in-store bakery",
                                                    "Giant/FairPrice house brand", "Swee Heng"],
                                        "why": "Lowest price per loaf.",
                                        "price_floor": "house brand"},
            "tier_2_direct_set": {"members": ["BreadTalk", "Four Leaves", "Paris Baguette",
                                              "Polar Puffs & Cakes", "Duke Bakery", "Tiong Bahru Bakery"],
                                  "why": "Same product: bread and buns bought on the go. All compete on the same shelf."},
            "tier_3_category_incumbent": {"members": ["BreadTalk - the iconic local chain, most outlets",
                                                      "Four Leaves - the everyday neighbourhood staple",
                                                      "Tiong Bahru Bakery - the artisan premium claim"],
                                          "why": "BreadTalk owns 'iconic local', Four Leaves 'everyday', TBB 'artisan'."},
            "tier_4_adjacent_crossover": {"members": ["cafe pastries", "convenience-store bread",
                                                      "dessert shops"],
                                          "why": "Same carb occasion, different product."},
            "tier_6_indirect": {"members": ["low-carb diets", "home baking"],
                                "why": "Reduces bread occasions."},
            "tier_7_new_entrants": {"members": ["Japanese/Korean bakery chains", "artisan microbakeries"],
                                    "why": "Derived from new openings."},
        },
    },
    "fast-food": {
        "product_category": "Fast food: quick counter-service meal",
        "price_spread": "wide at the item level (S$3.03-35.02), converged at the meal level (S$5 floor)",
        "tiers": {
            "tier_0_default": {"members": ["hawker meal ~S$4-5", "cook at home",
                                           "convenience-store meal", "skip the meal"],
                               "why": "Cheaper and equally fast. Most lunch occasions resolve here."},
            "tier_1_cheap_substitute": {"members": ["KFC Real Deals S$5", "McDonald's McSaver S$5",
                                                    "Jollibee Yumburger S$1.20", "hawker Western food"],
                                        "why": "A complete meal at the S$5 floor. TWO chains now share this price.",
                                        "price_floor": "S$1.20 single item / S$5 meal"},
            "tier_2_direct_set": {"members": ["McDonald's", "KFC", "Burger King", "Subway",
                                              "Jollibee", "Popeyes", "Domino's", "Pizza Hut"],
                                  "why": "Same product: a counter-service burger/chicken/pizza meal."},
            "tier_3_category_incumbent": {"members": ["McDonald's - the default, most outlets, McSaver S$5",
                                                      "KFC - the chicken specialist, $5 Real Deals",
                                                      "Burger King - the deepest-discount challenger"],
                                          "why": "Each holds a rung: default / chicken / discount."},
            "tier_4_adjacent_crossover": {"members": ["fast-casual (Shake Shack, Five Guys, Nando's)",
                                                      "food delivery", "hawker food as the real baseline"],
                                          "why": "Same meal, different price tier or channel."},
            "tier_6_indirect": {"members": ["health messaging", "cost-of-living cutting eating out"],
                                "why": "Reduces fast-food occasions."},
            "tier_7_new_entrants": {"members": ["Guzman y Gomez", "Japanese/Korean fast-casual entrants"],
                                    "why": "Derived from new openings."},
        },
    },
    "health-beauty": {
        "product_category": "Health and beauty retail: personal care and cosmetics",
        "price_spread": "moderate (Watsons/Guardian converged; Sephora premium above)",
        "tiers": {
            "tier_0_default": {"members": ["supermarket personal-care aisle", "don't buy",
                                           "use what you have"],
                               "why": "Cheaper or no purchase."},
            "tier_1_cheap_substitute": {"members": ["Unity Pharmacy (60+ stores, cheapest at regular price)",
                                                    "supermarket own-brand", "Shopee/Lazada online"],
                                        "why": "Lowest regular price for the same product.",
                                        "price_floor": "Unity regular price"},
            "tier_2_direct_set": {"members": ["Watsons (18% share)", "Guardian / DFI (14%)",
                                              "Unity Pharmacy", "Sephora (7%)", "Sa Sa"],
                                  "why": "Same product: personal care and beauty bought in store. Concentrated -- top 3 hold ~39%."},
            "tier_3_category_incumbent": {"members": ["Watsons - largest share at 18%, up from 16%",
                                                      "Guardian - the DFI rival, 120+ locations",
                                                      "Sephora - the premium beauty specialist"],
                                          "why": "Watsons owns 'biggest', Guardian 'neighbourhood', Sephora 'premium'."},
            "tier_4_adjacent_crossover": {"members": ["department-store beauty counters",
                                                      "pharmacy-only (prescription)", "dermatologist clinics"],
                                          "why": "Same need, different channel or authority."},
            "tier_6_indirect": {"members": ["minimalism / skin-barrier trend reducing products bought"],
                                "why": "Reduces purchase frequency."},
            "tier_7_new_entrants": {"members": ["RedMart Health", "iHerb", "Lazada Health", "Shopee Health"],
                                    "why": "Derived from market entries; all online-native."},
        },
    },
    "eyewear": {
        "product_category": "Eyewear: prescription spectacles",
        "price_spread": "wide (S$40-98+ with lenses)",
        "tiers": {
            "tier_0_default": {"members": ["keep the old pair", "contact lenses", "don't correct"],
                               "why": "Delays the purchase."},
            "tier_1_cheap_substitute": {"members": ["Lenskart S$40 with SALE60",
                                                    "online-only frames", "JB optical shops"],
                                        "why": "Lowest delivered price for a complete pair, lenses included.",
                                        "price_floor": "S$40"},
            "tier_2_direct_set": {"members": ["OWNDAYS (S$98 with lenses)", "Zoff (S$98 with lenses)",
                                              "Lenskart", "Spectacle Hut", "Pearle Vision", "MOL"],
                                  "why": "Same product: a complete pair of prescription glasses."},
            "tier_3_category_incumbent": {"members": ["OWNDAYS - the S$98-inclusive-lens standard, free progressives",
                                                      "Zoff - the Japanese rival at the same price point",
                                                      "Lenskart - the online price disruptor"],
                                          "why": "OWNDAYS owns 'transparent inclusive pricing', Lenskart 'cheapest'."},
            "tier_4_adjacent_crossover": {"members": ["LASIK surgery", "contact lenses", "online-only retailers"],
                                          "why": "Same need (sight correction), different product."},
            "tier_6_indirect": {"members": ["screen-time habits", "myopia management for children"],
                                "why": "Changes demand shape rather than removing it."},
            "tier_7_new_entrants": {"members": ["online-first frame brands", "myopia-control specialists"],
                                    "why": "Derived from new openings."},
        },
    },
    "furniture": {
        "product_category": "Furniture: home furnishing for a new flat",
        "price_spread": "wide (flat-pack vs solid teak vs leather)",
        "tiers": {
            "tier_0_default": {"members": ["second-hand / hand-me-down", "existing furniture",
                                           "built-ins from the renovation"],
                               "why": "No new purchase."},
            "tier_1_cheap_substitute": {"members": ["IKEA entry tier", "FortyTwo", "HipVan",
                                                    "Megafurniture", "IMM clearance"],
                                        "why": "Lowest total bill for a whole flat.",
                                        "price_floor": "IKEA entry tier"},
            "tier_2_direct_set": {"members": ["IKEA", "Courts", "Harvey Norman", "Castlery",
                                              "HipVan", "Scanteak", "Commune", "Cellini", "FortyTwo"],
                                  "why": "Same product: furniture for a home, competing on the same showroom floor."},
            "tier_3_category_incumbent": {"members": ["IKEA - the budget default, 3 stores",
                                                      "Castlery - mid-range design-led, founded 2013",
                                                      "Scanteak - solid teak specialist since 1974, 140+ stores"],
                                          "why": "IKEA owns 'cheap whole-flat', Castlery 'design without designer prices', Scanteak 'solid teak'."},
            "tier_4_adjacent_crossover": {"members": ["Taobao/Shopee direct imports", "custom carpentry",
                                                      "rental furniture"],
                                          "why": "Same need, different supply route."},
            "tier_6_indirect": {"members": ["delaying the move-in", "minimalism"],
                                "why": "Reduces the furnishing budget."},
            "tier_7_new_entrants": {"members": ["BoConcept", "King Living", "Grey & Sanders"],
                                    "why": "Derived from market entries in the premium band."},
        },
    },
    "preschool": {
        "product_category": "Preschool / childcare: full-day early education",
        "price_spread": "wide (S$163.50/mo anchor-capped vs premium private)",
        "tiers": {
            "tier_0_default": {"members": ["grandparent care", "stay-home parent",
                                           "part-time playgroup only"],
                               "why": "No fee at all. Most families start here."},
            "tier_1_cheap_substitute": {"members": ["PCF Sparkletots (kindergarten S$163.50/mo)",
                                                    "My First Skool (ECDA anchor operator, same fee cap)",
                                                    "MOE Kindergarten"],
                                        "why": "The ECDA Anchor Operator fee cap sets the effective price floor.",
                                        "price_floor": "S$163.50/mo (kindergarten, GST incl.)"},
            "tier_2_direct_set": {"members": ["PCF Sparkletots", "My First Skool", "EtonHouse",
                                              "MindChamps", "Little Olive Tree", "MapleBear"],
                                  "why": "Same product: full-day care and education for the same age group."},
            "tier_3_category_incumbent": {"members": ["PCF Sparkletots - the largest network in the country",
                                                      "My First Skool - the NTUC anchor operator",
                                                      "EtonHouse - the premium international-curriculum claim"],
                                          "why": "PCF owns 'largest', MFS 'anchor operator', EtonHouse 'premium'."},
            "tier_4_adjacent_crossover": {"members": ["enrichment classes instead of preschool",
                                                      "private tuition", "foreign-system international schools"],
                                          "why": "Same developmental need, different delivery and price tier."},
            "tier_6_indirect": {"members": ["falling birth rate", "WFH enabling home care"],
                                "why": "Reduces the number of children needing places."},
            "tier_7_new_entrants": {"members": ["new ECDA-registered operators", "boutique bilingual preschools"],
                                    "why": "Derived from ECDA registration listings."},
        },
    },
    "electronics": {
        "product_category": "Consumer electronics retail: TVs and appliances",
        "price_spread": "CONVERGED (flagships within 3-8% across retailers)",
        "tiers": {
            "tier_0_default": {"members": ["keep the old appliance", "don't buy", "second-hand"],
                               "why": "Delays the purchase."},
            "tier_1_cheap_substitute": {"members": ["Shopee / Lazada online", "Carousell",
                                                    "Mustafa", "parallel imports"],
                                        "why": "Lowest headline price, no showroom.",
                                        "price_floor": "online marketplace"},
            "tier_2_direct_set": {"members": ["Courts", "Harvey Norman", "Best Denki",
                                              "Gain City", "Challenger", "Mega Discount Store"],
                                  "why": "Same product: the same TV brands, on the same mall floor, at near-identical prices."},
            "tier_3_category_incumbent": {"members": ["Courts - the mass-market default, 1974",
                                                      "Harvey Norman - the big-format showroom",
                                                      "Best Denki - the Japanese-service claim"],
                                          "why": "The diagnostic: NO incumbent holds a distinct position -- see the converged-price finding."},
            "tier_4_adjacent_crossover": {"members": ["brand-direct stores (Sony, Samsung)",
                                                      "telco bundles", "online marketplaces"],
                                          "why": "Same product, different route to the buyer."},
            "tier_6_indirect": {"members": ["device longevity", "streaming reducing TV upgrades"],
                                "why": "Reduces replacement frequency."},
            "tier_7_new_entrants": {"members": ["online-first retailers", "brand-direct D2C"],
                                    "why": "Derived from market entries."},
        },
    },
}

# ---------------------------------------------------------------------------
# THE 50 COMPANIES
# label_source = the EXTERNAL published fact the prediction comes from
# prediction   = what the rubric's positioning dimensions should show
# ---------------------------------------------------------------------------
def C(cid, name, cat, price, prediction, label_source, differentiator, undercut, comps):
    return dict(cid=cid, name=name, cat=cat, price=price, prediction=prediction,
                label_source=label_source, differentiator=differentiator,
                undercut=undercut, comps=comps)


COMPANIES = [
    # --- bubble tea (wide spread: ends should separate, middle should not) -----
    C("BT01", "Mixue Singapore", "bubble-tea", "S$1.50-3.50",
      "HIGH mental_advantage expected (owns the price floor outright)",
      "Published price S$1.50 KingCone, the cheapest cup on the island; won by CREATING a new price floor",
      "The cheapest cup in Singapore. We created the S$1.50 price point and we own it. 30+ heartland and MRT outlets where students and families already are.",
      "Nothing structurally. Our brand is not premium and does not try to be.",
      ["R&B Tea", "Each-A-Cup", "koi", "Chicha San Chen"]),
    C("BT02", "KOI The Singapore", "bubble-tea", "S$5.50-7.50",
      "HIGH mental_advantage and HIGH defensibility expected (market leader, 20 yrs)",
      "Published store finder: 90 outlets counted 13 Sep 2026, the largest single network",
      "Premium handcrafted tea for nearly twenty years. 90 outlets, built entirely on word of mouth with no advertising.",
      "New imported brands get more press. As the biggest chain we attract more direct comparison.",
      ["LiHO TEA", "CHAGEE", "Chicha San Chen", "Mixue", "HEYTEA"]),
    C("BT03", "Chicha San Chen", "bubble-tea", "S$5.50+",
      "HIGH defensibility expected (own tea farms = hard to replicate)",
      "Published: brews from leaves grown on its OWN Taiwan tea farms; 32 outlets; 7 yrs in SG May 2026",
      "We grow our own tea in Taiwan and brew every cup to order. The aroma is closer to a pour-over than a concentrate.",
      "Pricier and slower. The queue is the price.",
      ["koi", "HEYTEA", "CHAGEE", "Mixue"]),
    C("BT04", "HEYTEA Singapore", "bubble-tea", "premium",
      "MID-HIGH mental_advantage expected (owns the cheese-foam idea)",
      "Published: cheezo salted cheese foam over fresh fruit tea; the app is the most actively maintained of any chain",
      "We invented the cheese foam topping. If the foam is why you buy, you buy from us.",
      "Others have copied the foam. We are premium-priced in a market with a S$1.50 floor.",
      ["Chicha San Chen", "koi", "CHAGEE", "Mixue"]),
    C("BT05", "R&B Tea", "bubble-tea", "from ~S$3.60",
      "LOW-MID expected (budget tier, no distinct position)",
      "Published price from ~S$3.60, budget tier; no distinctive claim in the category roundups",
      "Taiwanese brown sugar milk tea at a budget price. We are cheaper than the premium brands.",
      "We are not the cheapest either - Mixue undercuts us by more than half.",
      ["Mixue", "Each-A-Cup", "koi", "Chicha San Chen"]),
    C("BT06", "Each-A-Cup", "bubble-tea", "budget",
      "LOW-MID expected (48 outlets but no distinct claim)",
      "Published: 48 outlets counted 13 Sep 2026, founded 1999, budget tier; no distinctive positioning claim",
      "Homegrown since 1999, 48 outlets, budget price. We have been here through every wave.",
      "Longevity is not a position customers name. Newer brands are more visible.",
      ["Mixue", "R&B Tea", "koi", "LiHO TEA"]),
    C("BT07", "CHAGEE Singapore", "bubble-tea", "mid-tier",
      "HIGH mental_advantage expected (explicit anti-category position)",
      "Published: 46 outlets in 24 months, fastest riser; 'We're not a bubble tea brand' - Business Times",
      "We are not a bubble tea brand, we are a tea expert. Original leaf fresh milk tea, whole leaves brewed fresh with fresh milk.",
      "We are the newest of the big chains and we are not cheap.",
      ["koi", "LiHO TEA", "Chicha San Chen", "Mixue"]),
    C("BT08", "LiHO TEA", "bubble-tea", "mid-tier",
      "MID-HIGH mental_advantage expected (owns 'homegrown No.1')",
      "Published: ~84 outlets, founded 2017 Singapore; markets itself as 'a proud Singapore tea beverage brand'",
      "Singapore's own tea brand. Gula melaka, pandan and kaya - flavours from here, not imported.",
      "Our app is the only working channel; liho.sg is a parked domain.",
      ["koi", "CHAGEE", "Chicha San Chen", "Each-A-Cup"]),
    C("BT09", "Playmade", "bubble-tea", "mid-tier",
      "LOW-MID expected (a feature, not a position)",
      "Published: 'hand-rolled pearls of the day' is the signature; mid-tier price; no outlet-count leadership",
      "We hand-roll our pearls fresh every day in every store. You can taste the difference in the texture.",
      "A daily pearl flavour is a novelty, not a position. Anyone can roll pearls.",
      ["koi", "CHAGEE", "Sharetea", "R&B Tea"]),
    C("BT10", "Sharetea", "bubble-tea", "mid-tier",
      "LOW expected (Taiwanese chain with no local distinction)",
      "Published: Taiwanese, 1992 origin, mid-tier; signature winter melon tea; no distinct SG position claimed",
      "Authentic Taiwanese tea since 1992. Winter melon tea is our signature.",
      "We are one of many Taiwanese chains here and customers cannot easily tell us apart.",
      ["koi", "CHAGEE", "R&B Tea", "Playmade"]),

    # --- gym (wide spread + a fresh documented death) ------------------------
    C("GY01", "ActiveSG", "gym", "S$15-30/mo (or S$2.50/entry)",
      "HIGH mental_advantage expected (the price floor every gym is judged against)",
      "Published on activesgcircle.gov.sg: S$30/mo peak, S$15 off-peak, ~30 sites; 'the price floor every commercial gym is implicitly judged against'",
      "The cheapest way to train in Singapore. ~30 gyms islandwide, no contract, S$2.50 a visit if you prefer.",
      "Equipment is basic. Peak evenings are busy. Not 24/7.",
      ["Anytime Fitness", "Fitness First", "Virgin Active", "24/7 Fitness"]),
    C("GY02", "Anytime Fitness Singapore", "gym", "S$70-158/mo",
      "HIGH defensibility expected (161 outlets = hard to replicate footprint)",
      "Published: 161 outlets islandwide, all 24/7 keycard access, 4,000+ gyms globally via reciprocity",
      "161 gyms islandwide, every one open 24 hours with keycard access. Your membership works in 30+ countries.",
      "Each outlet is franchised and sets its own rate, so there is no single national price.",
      ["ActiveSG", "Fitness First", "Virgin Active", "Pure Fitness"]),
    C("GY03", "Fitness First Singapore", "gym", "S$200-225/mo",
      "MID-HIGH defensibility expected (established chain, publishes rates)",
      "Published on fitnessfirst.com/sg: Home Club S$200/mo, Passport S$225/mo, 14 clubs, zero joining fee",
      "14 clubs, 300+ group classes a month, Les Mills programming and Passport access across Asia.",
      "We are the second most expensive. True Fitness used to sit below us and has closed.",
      ["ActiveSG", "Anytime Fitness", "Virgin Active", "Pure Fitness"]),
    C("GY04", "Pure Fitness Singapore", "gym", "S$175-400/mo",
      "MID-HIGH defensibility expected (only 2 clubs = concentration, not reach)",
      "Published: 2 CBD clubs (Asia Square, Ocean Financial Centre), 25m lap pool, sauna, steam room, jacuzzi",
      "Two CBD clubs with 25-metre lap pools, sauna, steam room and integrated Pure Yoga access.",
      "Only two locations, both in the CBD. Pricing is enquiry-led and can reach S$400.",
      ["Virgin Active", "Fitness First", "Anytime Fitness", "ActiveSG"]),
    C("GY05", "Virgin Active Singapore", "gym", "S$220-265/mo",
      "MID-HIGH mental_advantage expected (owns 'premium recovery')",
      "Published: 5 clubs, pools at multiple sites, compression boots and oxygen therapy; S$41-92/week",
      "Premium clubs with pools, recovery amenities like compression boots and oxygen therapy, and 60+ weekly classes per club.",
      "The most expensive mainstream option, and only 5 clubs.",
      ["Pure Fitness", "Fitness First", "Anytime Fitness", "ActiveSG"]),
    C("GY06", "24/7 Fitness", "gym", "S$98-178/mo",
      "LOW-MID expected (undercuts the chains but no distinct position)",
      "Published: S$98/mo on 12-month, S$178 rolling; positioned as the cheaper 24/7 alternative",
      "24-hour access at S$98 a month on a 12-month plan - cheaper than any other full-service chain.",
      "Cheaper than the others, but Anytime Fitness has far more outlets and the same 24/7 promise.",
      ["Anytime Fitness", "ActiveSG", "Fitness First", "24/7 Fitness"]),
    C("GY07", "True Fitness Singapore", "gym", "was S$165-190/mo",
      "GATE or VERY LOW expected (documented closure 10 Sep 2026)",
      "DOCUMENTED DEATH: shut all Singapore clubs on 10 September 2026 into provisional liquidation; creditors' voluntary winding-up proposed 7 Oct 2026",
      "We were the mid-priced full-service chain between ActiveSG and Fitness First, with classes and premium equipment.",
      "We have closed. Members who paid in advance are unsecured creditors.",
      ["Fitness First", "Anytime Fitness", "ActiveSG", "Virgin Active"]),

    # --- supermarket ---------------------------------------------------------
    C("SM01", "NTUC FairPrice", "supermarket", "mainstream/value",
      "HIGH mental_advantage expected (the national default)",
      "Published: 125 stores, largest food retailer in Singapore; group revenue S$4.7bn FY2025; 1.7m app users",
      "Singapore's largest retailer. 125 stores, house brands priced 10-15% below branded alternatives, and we freeze prices on essentials at CNY.",
      "We face higher depreciation because of our mall presence, and our wider social mandate dilutes cost efficiency.",
      ["Sheng Siong", "Cold Storage", "Giant", "Don Don Donki"]),
    C("SM02", "Sheng Siong", "supermarket", "value",
      "HIGH mental_advantage expected (owns 'cheapest fresh')",
      "Published: 77 stores, peer-leading operating margin 8-9%, 'no frills, disciplined investment model underpins its margin leadership' (DBS)",
      "No-frills value with the freshest produce, at 77 stores close to HDB estates. Our margin leadership comes from cost discipline.",
      "Our central distribution centre is nearing capacity as we expand.",
      ["NTUC FairPrice", "Giant", "Cold Storage", "Don Don Donki"]),
    C("SM03", "Cold Storage", "supermarket", "premium",
      "MID-MENTAL expected (premium claim now contested)",
      "Published: 48 stores; DFI once held a near-monopoly in premium but FairPrice Finest expanded 9->39 stores; now owned by Macrovalue",
      "The premium grocery shop. Imported and specialty lines you will not find at the value chains.",
      "We no longer own premium. FairPrice Finest has 39 stores against our 48 and is closing the gap.",
      ["NTUC FairPrice", "Sheng Siong", "Giant", "Don Don Donki"]),
    C("SM04", "Giant", "supermarket", "value",
      "LOW-MID expected (value claim lost to Sheng Siong on scale)",
      "Published: 40 stores against FairPrice's 125 and Sheng Siong's 77; 'lags far behind' in a price-sensitive segment where scale drives procurement",
      "Everyday low prices for the household shop, at 40 stores.",
      "We are far smaller than FairPrice and Sheng Siong, so our procurement is weaker in a segment where scale decides price.",
      ["Sheng Siong", "NTUC FairPrice", "Cold Storage", "Don Don Donki"]),
    C("SM05", "Don Don Donki", "supermarket", "premium/value hybrid",
      "MID-HIGH mental_advantage expected (owns the Japanese-experience position)",
      "Published: listed among new entrants with a distinct 'Japanese experiential' format; grew store count islandwide",
      "Japanese imports, ready-to-eat food and a night-time experience you cannot get at a local supermarket.",
      "We are not cheap and not a full weekly shop. Most baskets still go to FairPrice or Sheng Siong.",
      ["NTUC FairPrice", "Sheng Siong", "Cold Storage", "Giant"]),

    # --- kopitiam ------------------------------------------------------------
    C("KP01", "Ya Kun Kaya Toast", "kopitiam", "sets from S$5.60",
      "HIGH mental_advantage and defensibility expected (the heritage standard)",
      "Published: heritage dating to a 1926 coffee stall, largest heritage chain; sets from S$5.60; 'the definitive kaya toast'",
      "Kaya toast and kopi made the same way since 1926. The standard by which the others are measured.",
      "We are the biggest, so we attract the most comparison. Rent is the main cost pressure.",
      ["Killiney Kopitiam", "Toast Box", "Chin Mee Chin", "Tong Ah"]),
    C("KP02", "Killiney Kopitiam", "kopitiam", "sets from ~S$5",
      "MID-HIGH mental_advantage expected (rival heritage claim, 1919)",
      "Published: shophouse coffee-shop lineage dated 1919; 'two of Singapore's most storied Hainanese kopitiam chains'",
      "Our Killiney Road shophouse lineage goes back to 1919 - older than our rival's claim. Same kaya toast, more menu breadth.",
      "Ya Kun has far more outlets and stronger brand recall. We are the second heritage brand.",
      ["Ya Kun Kaya Toast", "Toast Box", "Chin Mee Chin", "Tong Ah"]),
    C("KP03", "Toast Box", "kopitiam", "sets from ~S$5-7",
      "MID-MENTAL expected (modern mass-market, BreadTalk-owned)",
      "Published: BreadTalk group's modern mass-market take on the kopitiam format, mall-based",
      "Kopitiam food in a clean, air-conditioned mall format with consistent standards across every outlet.",
      "We are the modern imitation, not the original. Customers know we are owned by BreadTalk.",
      ["Ya Kun Kaya Toast", "Killiney Kopitiam", "Chin Mee Chin", "Tong Ah"]),
    C("KP04", "Chin Mee Chin", "kopitiam", "sets from ~S$5",
      "MID-HIGH defensibility expected (single iconic location = hard to copy)",
      "Published: listed among the best kaya toast spots 2026; a single iconic East Coast Road location",
      "One shophouse on East Coast Road, the original 1950s tiles and the same kaya recipe. No branches.",
      "Only one outlet and limited hours. Most people cannot get to us.",
      ["Ya Kun Kaya Toast", "Killiney Kopitiam", "Tong Ah", "Toast Box"]),

    # --- bakery --------------------------------------------------------------
    C("BK01", "BreadTalk", "bakery", "mid/budget",
      "HIGH mental_advantage expected (the iconic local chain)",
      "Published: the iconic local chain with the most outlets; sells 30 buns for a promotional price; 9-best-bakeries list 2026",
      "The most recognisable bakery chain in Singapore. Familiar buns, new flavours every month, an outlet in almost every mall.",
      "We are not halal-certified and not artisan. We are a mass chain.",
      ["Four Leaves", "Paris Baguette", "Tiong Bahru Bakery", "Polar Puffs & Cakes"]),
    C("BK02", "Four Leaves", "bakery", "budget/everyday",
      "MID defensibility expected (everyday staple, wide footprint)",
      "Published: 'the everyday neighbourhood bakery staple' in the 2026 nine-best roundup; not halal-certified",
      "The neighbourhood bakery Singaporeans grew up with. Familiar cakes and bread at everyday prices since 1980.",
      "We are seen as ordinary. Newer and premium brands get more attention.",
      ["BreadTalk", "Polar Puffs & Cakes", "Paris Baguette", "Tiong Bahru Bakery"]),
    C("BK03", "Paris Baguette", "bakery", "premium",
      "MID-HIGH mental_advantage expected (owns 'Korean premium')",
      "Published: halal-certified; positioned as the premium Korean bakery chain in the 2026 nine-best roundup",
      "Korean bakery design and flavours you will not find in a local chain. Café seating in every store.",
      "We are premium-priced and there are far fewer outlets than BreadTalk.",
      ["BreadTalk", "Tiong Bahru Bakery", "Four Leaves", "Polar Puffs & Cakes"]),
    C("BK04", "Tiong Bahru Bakery", "bakery", "premium artisan",
      "MID-HIGH defensibility expected (artisan position, founder-chef association)",
      "Published: 'the artisan premium claim'; French-trained baker association; 9-best list 2026; not halal",
      "French butter croissants and sourdough made fresh in each bakery, not delivered from a central factory.",
      "Fewer outlets, higher prices, and we are not halal-certified.",
      ["Paris Baguette", "BreadTalk", "Four Leaves", "Polar Puffs & Cakes"]),
    C("BK05", "Polar Puffs & Cakes", "bakery", "budget",
      "LOW-MID expected (a product, not a position)",
      "Published: halal-certified; known primarily for curry puffs and a legacy cake range; no distinct premium or artisan claim",
      "Halal-certified curry puffs and cakes, made in Singapore since 1925.",
      "We are known for one product. Customers do not think of us as a bakery destination.",
      ["BreadTalk", "Four Leaves", "Paris Baguette", "Tiong Bahru Bakery"]),

    # --- fast food -----------------------------------------------------------
    C("FF01", "McDonald's Singapore", "fast-food", "McSaver from S$5",
      "HIGH mental_advantage expected (the default, most outlets)",
      "Published: McSaver Meals from S$5 (Filet-O-Fish, McChicken, Smoky Beef); 'Singapore's most downloaded F&B app'",
      "The most outlets, the most downloaded app in F&B, and a complete meal from S$5 on the McSaver line.",
      "We are the default, so we are compared on price by everyone including the other chains.",
      ["KFC", "Burger King", "Subway", "KFC Real Deals"]),
    C("FF02", "KFC Singapore", "fast-food", "Real Deals from S$5",
      "HIGH mental_advantage expected (owns 'the chicken place')",
      "Published: $5 Real Deals range replacing the old deal menu; 8pc bucket S$28.30; the most expensive flagship item at S$35.02",
      "Fried chicken is what we do and everyone knows it. Real Deals puts a complete meal at S$5 on weekdays.",
      "Our deals are weekday-only and dine-in only, not on delivery, and excluded at Jewel, Sentosa and the Zoo.",
      ["McDonald's", "Burger King", "Popeyes", "Jollibee"]),
    C("FF03", "Burger King Singapore", "fast-food", "coupons to 62% off",
      "MID-MENTAL expected (discount-led, not position-led)",
      "Published: 'the most aggressive of the six on pure percentage savings', up to 62% off with coupon DL8",
      "The deepest discounts of any chain. DL8 gets 9pc nuggets and a drink for S$5 against S$13.15.",
      "Our position is discounting itself, which any rival can copy with a coupon. Airport outlets excluded.",
      ["McDonald's", "KFC", "Subway", "Jollibee"]),
    C("FF04", "Subway Singapore", "fast-food", "Everyday Value S$6.80",
      "MID-mental_advantage expected (owns 'not fried')",
      "Published: Everyday Value Meal S$6.80 (6-inch sub, cookie, drink); 'the only one of the cheap meals that is not fried'",
      "The only cheap meal that is not fried, with free vegetable toppings and a sub made in front of you.",
      "We are dearer than the S$5 full meals at KFC and McDonald's, and only five subs on the value line.",
      ["McDonald's", "KFC", "Burger King", "Jollibee"]),
    C("FF05", "Jollibee Singapore", "fast-food", "value",
      "MID mental_advantage expected (owns 'Filipino comfort')",
      "Published: Yumburger S$1.20 - among the cheapest single items of all 14 chains; Chickenjoy S$4.25",
      "Filipino fried chicken and sweet-style spaghetti. Chickenjoy and the Yumburger at S$1.20.",
      "Outside the Filipino community we are a small chain with few outlets.",
      ["McDonald's", "KFC", "Burger King", "Subway"]),
    C("FF06", "Shake Shack Singapore", "fast-food", "premium (ShackBurger S$12.17)",
      "MID-HIGH mental_advantage expected (owns 'premium burger')",
      "Published: ShackBurger S$12.17, shake US$8.25 - premium tier in the 14-chain price comparison",
      "Premium burgers and shakes, made with better beef than the value chains, in a designed space.",
      "We cost more than twice a McDonald's meal and there are very few outlets.",
      ["McDonald's", "Burger King", "Five Guys", "KFC"]),

    # --- health & beauty -----------------------------------------------------
    C("HB01", "Watsons Singapore", "health-beauty", "value/mass",
      "HIGH mental_advantage expected (largest share, 18%)",
      "Published: Watsons held the largest share at 18% in 2025, up from 16% in 2020 (Euromonitor)",
      "The largest health and beauty chain in Singapore, with the widest range, exclusive brands and the strongest loyalty programme.",
      "We are a mass retailer. Premium brands first list at Sephora, not with us.",
      ["Guardian", "Unity Pharmacy", "Sephora", "Sa Sa"]),
    C("HB02", "Guardian Singapore", "health-beauty", "value/mass",
      "MID-HIGH mental_advantage expected (the entrenched rival, 14%)",
      "Published: DFI Retail Group held 14% share in 2025; 120+ locations, 'strong in HDB neighbourhood malls'",
      "120+ stores in HDB neighbourhood malls, so we are the pharmacy people walk past every day. 2m monthly visitors.",
      "Watsons is bigger and has grown its share while ours has been flat.",
      ["Watsons", "Unity Pharmacy", "Sephora", "Sa Sa"]),
    C("HB03", "Unity Pharmacy", "health-beauty", "cheapest at regular price",
      "MID-MENTAL expected (cheapest claim, but limited range)",
      "Published: Unity is cheapest at regular price among the three chains, 60+ stores, integrated with public healthcare",
      "The cheapest regular prices of the three chains, 60+ stores, and ties to public health programmes and insurance-billable products.",
      "Our smaller outlets have a limited range and we have fewer stores than Watsons or Guardian.",
      ["Watsons", "Guardian", "Sephora", "Sa Sa"]),
    C("HB04", "Sephora Singapore", "health-beauty", "premium (7% share)",
      "MID-HIGH mental_advantage expected (owns the premium beauty position)",
      "Published: Sephora Singapore held 7% share in 2025 (Euromonitor); 'premium international beauty brands list at Sephora first'",
      "The premium beauty destination. Exclusive international brands list with us first before going to the mass chains.",
      "We hold 7% share against Watsons' 18%, and we do not sell household or pharmacy essentials.",
      ["Watsons", "Guardian", "Unity Pharmacy", "Sa Sa"]),

    # --- eyewear -------------------------------------------------------------
    C("EW01", "OWNDAYS Singapore", "eyewear", "S$98 with lenses",
      "HIGH mental_advantage expected (owns transparent inclusive pricing)",
      "Published: 'Glasses from $98 with standard high-index aspheric lenses of any power included (no lens top-up), plus FREE Enhanced Progressive Lenses'",
      "One price of S$98 including high-index lenses at any power, with progressive lenses free. No top-ups and no hidden extras.",
      "Our frames are mass-market rather than designer, and some concept stores are excluded from the free-progressive offer.",
      ["Zoff", "Lenskart", "Spectacle Hut", "Pearle Vision"]),
    C("EW02", "Zoff Singapore", "eyewear", "S$98 with lenses",
      "MID-HIGH mental_advantage expected (same price point, Japanese design claim)",
      "Published: $98 with lenses, matching OWNDAYS; positioned as the Japanese rival at the same inclusive price",
      "Japanese-designed frames at the same S$98 all-inclusive price, with lens options for focus-adjustment comfort.",
      "We are priced identically to OWNDAYS, so customers have no price reason to choose us over them.",
      ["OWNDAYS", "Lenskart", "Spectacle Hut", "Pearle Vision"]),
    C("EW03", "Lenskart Singapore", "eyewear", "S$40 with SALE60",
      "MID-HIGH mental_advantage expected (owns 'cheapest complete pair')",
      "Published: 'Lenskart $40 with SALE60' - the lowest delivered price for a complete pair in the 2026 comparison",
      "A complete pair of prescription glasses from S$40, online-first with in-store eye tests.",
      "We compete only on price. Frame quality and service are perceived as below the Japanese chains.",
      ["OWNDAYS", "Zoff", "Spectacle Hut", "Pearle Vision"]),
    C("EW04", "Spectacle Hut", "eyewear", "mid-premium",
      "LOW-MID expected (no distinct price or design claim)",
      "Published: included in the 2026 eyewear comparisons with no distinctive price, design or service claim attached to it",
      "Established Singapore optical chain with designer frame brands and in-store optometrists.",
      "We are neither the cheapest nor the most transparently priced, and we have no distinctive claim customers name.",
      ["OWNDAYS", "Zoff", "Lenskart", "Pearle Vision"]),

    # --- furniture -----------------------------------------------------------
    C("FU01", "IKEA Singapore", "furniture", "entry/budget",
      "HIGH mental_advantage expected (owns 'cheap whole flat')",
      "Published: 3 stores, New Home Package $300 voucher per $2,000 spend, entry-tier benchmark; 'furnish a 4-room flat for $15,000'",
      "Flat-pack furniture that furnishes a whole flat at the lowest total bill, with a year-round New Home Package that returns $300 per $2,000 spent.",
      "Self-assembly costs your time, and entry-tier pieces are the ones people most often replace.",
      ["Castlery", "Scanteak", "HipVan", "Courts"]),
    C("FU02", "Castlery", "furniture", "mid-range",
      "MID-HIGH mental_advantage expected (owns 'design without designer prices')",
      "Published: 'a Singapore-founded brand known for modern designer furniture at mid-range prices', founded 2013, direct supply chain",
      "Design-led furniture at mid-range prices through a direct supply chain, so you skip the designer markup.",
      "Online-first means you buy before you sit on it, and delivery takes weeks.",
      ["IKEA", "Scanteak", "HipVan", "Commune"]),
    C("FU03", "Scanteak", "furniture", "mid-premium",
      "HIGH defensibility expected (solid teak specialisation since 1974)",
      "Published: 'has been selling teak furniture since 1974 and now runs more than 140 stores across Singapore, Japan and Taiwan'; solid teak that can be sanded and re-oiled",
      "Solid teak since 1974, plantation-sourced. In this humidity, teak is the wood that lasts and can be re-oiled a decade later.",
      "Solid teak costs what it costs - several times flat-pack for the same item.",
      ["IKEA", "Castlery", "Commune", "Cellini"]),
    C("FU04", "Cellini", "furniture", "premium",
      "MID-HIGH defensibility expected (in-house manufacturing, leather specialisation)",
      "Published: 'Premium - leather sofas and full sets, a sofa meant to last a decade'; in-house manufacturing; over $1,000 free delivery",
      "Leather sofas made in our own factory, built to last a decade. You can feel the materials before you commit.",
      "Premium pricing with a $1,000 delivery threshold, and we are not a whole-flat solution.",
      ["IKEA", "Scanteak", "Castlery", "Commune"]),

    # --- preschool -----------------------------------------------------------
    C("PS01", "PCF Sparkletots", "preschool", "S$163.50/mo kindergarten",
      "HIGH mental_advantage expected (largest network, anchor fee cap)",
      "Published: 'the biggest preschool network in Singapore'; ECDA Anchor Operator so the fee cap applies; kindergarten S$163.50/mo GST-inclusive",
      "The largest preschool network in the country, as an ECDA Anchor Operator with fees capped and GST already included.",
      "Being the biggest and the cheapest means we are not seen as premium. Parents who want a brand-name curriculum look elsewhere.",
      ["My First Skool", "EtonHouse", "MindChamps", "Little Olive Tree"]),
    C("PS02", "My First Skool", "preschool", "anchor-capped (same as PCF)",
      "HIGH mental_advantage expected (NTUC anchor operator, same cap)",
      "Published: an ECDA Anchor Operator so the same fee cap applies; part of NTUC, the social-enterprise group",
      "An ECDA Anchor Operator under the same fee cap as PCF, backed by NTUC, with subsidised fees for eligible families.",
      "We are priced the same as PCF and have fewer centres, so there is little reason to choose us specifically.",
      ["PCF Sparkletots", "EtonHouse", "MindChamps", "Little Olive Tree"]),

    # --- electronics (CONVERGED price: the negative control) -----------------
    C("EL01", "Courts Singapore", "electronics", "converged",
      "MID expected (no distinct position; price converged at 3-8%)",
      "Published: 'Samsung, LG, Sony, and TCL flagships land within 3 to 8 percent of each other across Courts, Harvey Norman, and Best Denki, and the gap flips depending on the week'",
      "Singapore's mass-market electronics retailer since 1974, with instalment plans and physical stores where you can see the product.",
      "Every retailer sells the same brands within a few percent, so customers choose on the nearest store or the week's promotion.",
      ["Harvey Norman", "Best Denki", "Gain City", "Challenger"]),
    C("EL02", "Harvey Norman Singapore", "electronics", "converged",
      "MID expected (no distinct position; price converged at 3-8%)",
      "Published: same 3-8% price band as Courts and Best Denki; big-format showrooms",
      "Large-format showrooms where you can compare the whole range in one visit, with interest-free finance.",
      "Our prices are within a few percent of every rival, so there is no price reason to choose us.",
      ["Courts", "Best Denki", "Gain City", "Challenger"]),
    C("EL03", "Best Denki Singapore", "electronics", "converged",
      "MID expected (no distinct position; price converged at 3-8%)",
      "Published: same 3-8% price band as Courts and Harvey Norman; Japanese-service positioning claim",
      "Japanese retail service standards with trained staff who can explain the difference between models.",
      "We are in the same few-percent price band as everyone and the Japanese-service claim is not something customers test before buying.",
      ["Courts", "Harvey Norman", "Gain City", "Challenger"]),
    C("EL04", "Gain City", "electronics", "converged",
      "MID expected (no distinct position; price converged at 3-8%)",
      "Published: listed among the visible Singapore electronics players in the same converged price band; aircon/installation strength",
      "Air-conditioning and appliance installation done by our own technicians, with showroom displays of full systems.",
      "We sell the same brands at the same prices as the big three, and installation expertise is not what most shoppers compare.",
      ["Courts", "Harvey Norman", "Best Denki", "Challenger"]),
]

TIER_ORDER = ["tier_0_default", "tier_1_cheap_substitute", "tier_2_direct_set",
              "tier_3_category_incumbent", "tier_4_adjacent_crossover",
              "tier_6_indirect", "tier_7_new_entrants"]

# map case-id prefix -> category
PREFIX = {"BT": "bubble-tea", "GY": "gym", "SM": "supermarket", "KP": "kopitiam",
          "BK": "bakery", "FF": "fast-food", "HB": "health-beauty",
          "EW": "eyewear", "FU": "furniture", "PS": "preschool", "EL": "electronics"}

written = {}
for c in COMPANIES:
    cat = CATS[c["cat"]]
    derived = {}
    for t in TIER_ORDER:
        if t in cat["tiers"]:
            derived[t] = cat["tiers"][t]
    derived["_derivation_method"] = (
        "Derived from the PRODUCT CATEGORY (%s), not the owner's list. Price spread in "
        "this category: %s. Tiers follow the eight-tier frame: default/no-purchase, cheap "
        "substitute, direct set, category incumbent (the rungs of the customer's mental "
        "ladder), adjacent crossover, indirect, and new entrants derived from public "
        "opening records." % (cat["product_category"], cat["price_spread"]))

    payload = {
        "_meta": {
            # sanitise: a business name containing "/" (e.g. "24/7 Fitness") produced a
            # case id with a slash in it, which broke the run filename. Case ids must be
            # filesystem-safe.
            "case": (c["cid"] + "-" + c["name"].split()[0].lower().replace("'", ""))
                    .replace("/", "-").replace("\\", "-").replace("&", "and"),
            "business": c["name"],
            "product_category": cat["product_category"],
            "category_price_spread": cat["price_spread"],
            "purpose": "FRESH-DATA VALIDITY TEST (n=50 across 11 categories). The "
                       "competitive set is derived per PRODUCT CATEGORY and held constant "
                       "across its members, so the business is the only variable.",
            "PRE_REGISTERED_PREDICTION": c["prediction"],
            "LABEL_SOURCE": c["label_source"],
            "label_is_external": True,
            "sealed_before_run": True,
            "sources": [c["label_source"]],
            "authoring_note": "FORM DATA reconstructed by the analyst from public "
                              "sources. The LABEL is external and published; the form "
                              "is thinner than a real submission. This is the known "
                              "weakness of the test.",
        },
        "form": {
            "business_name": c["name"],
            "role": "Founder / country management",
            "company_size_band": "10-500",
            "city": "Singapore",
            "category": cat["product_category"],
            "positioning_sentence": c["differentiator"].split(".")[0] + ".",
            "differentiator": c["differentiator"],
            "undercut_on": c["undercut"],
            "your_price_point": c["price"],
            "their_price_point": "See the derived competitive set for the category price ladder.",
            "competitors_named_count": "3-5",
        },
        "competitors_named": c["comps"],
        "derived_competitive_set": derived,
    }
    fn = OUT / (c["cid"] + ".json")
    fn.write_text(json.dumps(payload, indent=2, ensure_ascii=False))
    written[c["cid"]] = {"name": c["name"], "cat": c["cat"],
                         "prediction": c["prediction"], "price": c["price"],
                         "label_source": c["label_source"]}

(OUT / "_index.json").write_text(json.dumps({
    "n": len(written),
    "categories": {k: CATS[k]["product_category"] for k in CATS},
    "category_price_spreads": {k: CATS[k]["price_spread"] for k in CATS},
    "companies": written,
}, indent=2, ensure_ascii=False))

from collections import Counter
cnt = Counter(v["cat"] for v in written.values())
print("wrote %d input files to inputs-v2/" % len(written))
print()
print("%-16s %s" % ("category", "n"))
for k, n in cnt.most_common():
    print("  %-14s %d" % (k, n))
print()
print("total:", sum(cnt.values()), "across", len(cnt), "categories")
